### ISSUE TITLE
Bomb plant error

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [partiusfabaa/cs2-ranks#21]
20:56:51 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ranks.Ranks.UpdateUserStatsLocal(CCSPlayerController player, String msg, Int32 exp, Boolean increase, Int32 kills, Int32 death, Int32 assist, Int32 shoots, Int32 hits, Int32 headshots, Int32 roundwin, Int32 roundlose)
   at Ranks.Ranks.<>cDisplayClass31_0.<BombEvents>b3(EventBombPlanted event, GameEventInfo _)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>cDisplayClass3_0.<.ctor>b0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

**Comment by lostsoul6** [comment]
Hi @BrutalCSEjziponken , I'm getting the same error . did you manage to solve it?

**Comment by BrutalCSEjziponken** [comment]
> Hi @BrutalCSEjziponken , I'm getting the same error . did you manage to solve it?

No, are u running retakes? Also are u using the LR version?

**Comment by partiusfabaa** [comment]
https://github.com/partiusfabaa/cs2-ranks/releases/tag/v1.0.6.2

try
