### ISSUE TITLE
System.AccessViolationException: Attempted to read or write protected memory

### ISSUE THREAD

**Issue by lostsoul6** [partiusfabaa/cs2-ranks#23]
Hi @partiusfabaa ,

I notice this error printed on my console a lot : 

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadByte(IntPtr ptr, Int32 ofs)
   at CounterStrikeSharp.API.Core.ScriptContext.GetResult(Type type, Byte* ptr) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 451
   at CounterStrikeSharp.API.Core.NativeAPI.GetSchemaValueByName[T](IntPtr instance, Int32 returntype, String classname, String propname) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1101
   at CounterStrikeSharp.API.Core.CBasePlayerController.get_PlayerName() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Objects.g.cs:line 5103
   at Ranks.Ranks.EventPlayerDeath(EventPlayerDeath event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
2024-01-22 00:43:37.808 +03:30 [EROR] (cssharp:Core) Error invoking callback

```

I'm using CSS v144 . What is this error and how do I solve it?

**Comment by partiusfabaa** [comment]
i'll fix it today

**Comment by lostsoul6** [comment]
@partiusfabaa thanks . Also I have another question . the !top command only works when there are a few players on the server . most of the time it doesn't work. any idea why and how to fix it?

**Comment by partiusfabaa** [comment]
i thought i fixed it today, or is it still the same?

**Comment by partiusfabaa** [comment]
https://github.com/partiusfabaa/cs2-ranks/releases/tag/v1.0.6.1

**Comment by lostsoul6** [comment]
@partiusfabaa I updated to the last version . the error seems to be fixed . Also the !top command worked with 6 players in server . I will check again once server has more players and will get back to you in case the issue is not fixed . thanks for you efforts .

**Comment by lostsoul6** [comment]
@partiusfabaa update : today I tried !top in server when there were like 5 players in it and it didn't work . tried 3-4 times . chat or console doesn't print anything of note so I can understand why it's happening .

**Comment by partiusfabaa** [comment]
Okay, thanks. I'll take a look tomorrow

**Comment by lostsoul6** [comment]
@partiusfabaa I noticed something , last night I had a full server with 18/18 players and typed !top and it worked but earlier that day with 5 players in server !top didn't work . It seems totally random now . I thought if there were many players in server it doesn't work but I think the number of players is not the issue . If it was the issue , then how did it work with 18 players in the server and didn't work with 5 players?
