### ISSUE TITLE
Shared API not loading

### ISSUE THREAD

**Issue by damian5602** [partiusfabaa/cs2-ranks#40]
Hi, I'm just trying to install this plugin but i'm getting this error:
`2024-04-03 18:45:24.295 +02:00 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/servers/users/srv79503/CS2/game/csgo/addons/counterstrikesharp/plugins/Ranks/Ranks.dll
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'RanksApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 118
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 52
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 34
System.IO.FileNotFoundException: Could not load file or assembly 'RanksApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`
It's looks like counterstrikesharp is not using shared folder, any solution for this problem?

**Comment by damian5602** [comment]
Updated counterstrikesharp and everything works fine
